superlists/lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r"^new$", views.new_list, name="new_list"),
    url(r"^(\d+)/$", views.view_list, name="view_list"),
    url(r"^(\d+)/add_item$", views.add_item, name="add_item"),
]

superlists/superlists/urls.py
from django.conf.urls import include, url
from lists import views
from lists import urls as list_urls

urlpatterns = [
    url(r"^$", views.home_page, name="home"),
    url(r"^lists/", include(list_urls)),
]

superlists/lists/models.py
from django.db import models

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)
    

superlists/lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List


def home_page(request):
    return render(request, "home.html")


def new_list(request):
    new_item_text = request.POST.get("item_text", "")
    new_list = List.objects.create()
    Item.objects.create(text=new_item_text, list=new_list)
    return redirect(f"/lists/{new_list.id}/")


def view_list(request, list_id):
    vlist = List.objects.get(id=list_id)
    items = Item.objects.filter(list=vlist)
    return render(request, "list.html", {"list": vlist})


def add_item(request, list_id):
    vlist = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=vlist)
    return redirect(f"/lists/{vlist.id}/")

superlists/lists/templates/base.html
<html>
  <head>
    <title>To-Do lists</title>
    <link href="/static/css/site.css" rel="stylesheet">
  </head>
  <body>
    <h1>{% block header_text %}{% endblock %}</h1>
    <form method="POST" action="{% block form_action %}{% endblock %}">
      {% csrf_token %}
      <label id="new_item_label" for="new_item">Enter a to-do item</label>
      <input id="new_item" name="item_text" type="text" />
      <input type="submit" value="Add New Item" />
    </form>
    {% block table %}{% endblock %}
  </body>
</html>

superlists/lists/templates/home.html
{% extends "base.html" %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

superlists/lists/templates/list.html
{% extends "base.html" %}

{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}
{% block table %}
<table id="id_list_table">
  {% for item in list.item_set.all %}
  <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
  {% endfor %}
</table>
{% endblock %}